# Free checklists: one per site. Each item: (text, why-or-empty)
TOOLS = {
 "exit-plan": {
  "site": "exit", "slug": "exit-plan",
  "title": "The Exit Plan Checklist",
  "eyebrow": "StoryBook Exit · Free checklist",
  "lead": "The work buyers will test, in the order it gets built. Check off what's already true. What's left is your exit plan.",
  "check_label": "Done",
  "bullets": ["Your exit goals, team and timeline", "The six areas buyers test", "What's done and what's left, in one list"],
  "groups": [
   ("Decide what the exit looks like", "Start from the finish line.", [
     ("I've picked a target window for stepping back or selling", "Two to three years out gives you time to fix what buyers discount."),
     ("I know what kind of exit I want", "Sell to an outside buyer, family, managers or employees, or keep it and step back."),
     ("I know what I need from the sale", "Work out your retirement number with a financial planner, not a guess."),
     ("I've decided what my role will be after the sale", "Stay on for a transition, consult, or walk away."),
     ("My advisor team is named", "CPA, attorney and financial planner now. A broker or M&A advisor later.")]),
   ("Financial quality", "Clean, consistent books a buyer can rely on.", [
     ("Three years of reconciled financial statements", ""),
     ("Tax returns tie to the books", "Differences are explained in writing."),
     ("The chart of accounts is consistent year to year", ""),
     ("Owner add-backs are listed and supported", "Personal or one-time expenses, with receipts."),
     ("Personal spending runs outside the business", ""),
     ("The books close every month", "Same steps, same timing, every month."),
     ("I can produce accrual-basis reports", "Buyers and lenders compare accrual numbers.")]),
   ("Profit and efficiency", "Find the leaks before a buyer does.", [
     ("I know my margin by service or product", ""),
     ("Vendor contracts and prices were reviewed this year", ""),
     ("Unused software and subscriptions are cancelled", ""),
     ("Pricing was reviewed in the last 12 months", ""),
     ("I run a 13-week cash forecast", "")]),
   ("Team strength", "The people a buyer will inherit.", [
     ("There's an org chart with every role named", ""),
     ("Every key job has a trained backup", ""),
     ("Core procedures are written down by the people who do them", ""),
     ("Key employees have a reason to stay through a sale", "")]),
   ("Owner independence", "The business runs without you in the room.", [
     ("I've listed everything only I can do", "That list is your handoff plan."),
     ("Day-to-day approvals are delegated", ""),
     ("Key customer relationships are held by the team, not just me", ""),
     ("I've taken two weeks off and the business ran fine", ""),
     ("I've tested a 30-day absence", "")]),
   ("Company memory and records", "Nothing important lives only in someone's head.", [
     ("Contracts, leases and licenses are organized in one place", ""),
     ("Leases and key contracts can be transferred to a buyer", "Check the assignment clauses."),
     ("The company, not a person, owns the domain, logins and brand", ""),
     ("The minute book and ownership records are current", "")]),
   ("Buyer readiness", "Evidence ready before anyone asks.", [
     ("No single customer is too large a share of revenue", ""),
     ("Recurring revenue is documented", ""),
     ("A data room folder is started", "Financials, tax returns, contracts, customer list."),
     ("I have a current valuation estimate", ""),
     ("I know what a quality-of-earnings review looks for", ""),
     ("I know how I'll choose a broker or advisor", "")]),
  ],
  "notes": [("biggest", "The biggest thing standing between me and an exit"), ("when", "When I'd like to be done")],
 },
 "qbo-learning": {
  "site": "gaap", "slug": "qbo-learning",
  "title": "The QuickBooks Learning List",
  "eyebrow": "Train the GAAP · Free checklist",
  "lead": "Check what you want to understand better: QuickBooks Online topics, the reports, and the GAAP principles behind them. No wrong answers. This is how we plan your training.",
  "check_label": "Want to learn",
  "bullets": ["20 QuickBooks Online topics", "18 reports to understand better", "The five GAAP principles"],
  "groups": [
   ("QuickBooks Online: what I want to learn more about", "The how and the why.", [
     ("Bank feeds and rules, and when not to trust them", ""),
     ("Reconciling bank and credit card accounts", ""),
     ("Payments to deposit (undeposited funds)", ""),
     ("Merchant deposits and fees, gross vs. net", ""),
     ("Customer refunds, credits and write-offs", ""),
     ("Vendor credits and bill payments", ""),
     ("Loans: splitting principal and interest", ""),
     ("Owner contributions, draws and distributions", ""),
     ("Payroll entries and payroll liabilities", ""),
     ("Sales tax setup and filing", ""),
     ("Inventory and cost of goods sold", ""),
     ("Fixed assets and depreciation", ""),
     ("Prepaid expenses and accruals", ""),
     ("Journal entries: when to use them and how", ""),
     ("Classes and locations", ""),
     ("Recurring transactions", ""),
     ("1099 vendor tracking", ""),
     ("Closing the books and the closing-date password", ""),
     ("Using the audit log", ""),
     ("Why the CPA changed my entries at year end", "")]),
   ("Reports I want to understand better", "Check each one you'd like walked through.", [
     ("Profit and Loss", ""),
     ("Profit and Loss by month or comparison", ""),
     ("Balance Sheet", ""),
     ("Statement of Cash Flows", ""),
     ("Accounts Receivable Aging", ""),
     ("Accounts Payable Aging", ""),
     ("General Ledger", ""),
     ("Trial Balance", ""),
     ("Transaction Detail by Account", ""),
     ("Reconciliation reports", ""),
     ("Sales by Customer and by Product", ""),
     ("Expenses by Vendor", ""),
     ("Profit and Loss by Class or Location", ""),
     ("Budget vs. Actuals", ""),
     ("Payroll Summary", ""),
     ("Sales Tax Liability", ""),
     ("Journal report", ""),
     ("Audit Log", "")]),
   ("The GAAP principles behind the work", "Check any you'd like explained with real examples.", [
     ("Revenue Recognition", "Record revenue when it's earned, not when cash arrives."),
     ("Matching (Expense Recognition)", "Record expenses with the revenue they helped earn."),
     ("Historical Cost", "Record assets at what you paid."),
     ("Full Disclosure", "Include every material fact a reader needs."),
     ("Consistency", "Use the same methods period to period.")]),
  ],
  "notes": [("role", "My role (bookkeeper, owner, office manager...)"), ("stuck", "The thing in QuickBooks I'm most stuck on right now")],
 },
 "goals-vision": {
  "site": "riltr", "slug": "goals-vision",
  "title": "The Goals & Vision Checklist",
  "eyebrow": "Run It Like the Rich · Free checklist",
  "lead": "Pick the goals that matter to you, then work through the vision steps. Check them off as you go. Edit the plan, not the mission.",
  "check_label": "My goal",
  "bullets": ["Owner and business goals to choose from", "Seven vision steps to check off", "A one-line vision you can share with your team"],
  "groups": [
   ("Goals for me, the owner", "Check the ones you want.", [
     ("Take a real vacation without checking in", ""),
     ("Work set hours most weeks", ""),
     ("Pay myself on a schedule", ""),
     ("Build retirement savings from the business", ""),
     ("Know my numbers every Monday", ""),
     ("Step back from day-to-day operations", ""),
     ("Have the option to sell someday", "")]),
   ("Goals for the business", "Check the ones you want.", [
     ("Clean, current books every month", ""),
     ("Never miss a filing or renewal deadline", ""),
     ("Grow revenue", ""),
     ("Improve margins", ""),
     ("Hire or promote a key role", ""),
     ("Add a location, territory or service line", ""),
     ("Qualify for financing", ""),
     ("Build a team that runs without me", "")]),
   ("Vision steps", "Check each one when it's done.", [
     ("I wrote down what the business looks like in three years", ""),
     ("I picked my top three priorities for this quarter", ""),
     ("I chose five to seven numbers that define success", "Cash, sales, margin, what customers owe you, what you owe."),
     ("I set a weekly, monthly and yearly rhythm", "When you review numbers, close the books and plan."),
     ("I put the plan on one page", ""),
     ("I shared the vision with my team", ""),
     ("I put a quarterly review on the calendar", "")]),
  ],
  "notes": [("vision", "In three years, my business..."), ("first", "The one thing I'll change this month")],
 },
}

# Which free checklist each site's header offers
FREEBIE = {
 "hub":   ("clean", "The Clean Start Checklist", "Every Admin, Books and Compliance setup step for a Florida business, in one place.",
           ["48 setup steps, from forming the company to the monthly close", "Sales tax lookup by ZIP code", "A 12-month compliance calendar"]),
 "hq":    ("clean", "The Clean Start Checklist", "Every Admin, Books and Compliance setup step for a Florida business, in one place.",
           ["48 setup steps, from forming the company to the monthly close", "Sales tax lookup by ZIP code", "A 12-month compliance calendar"]),
 "vhq":   ("clean", "The Clean Start Checklist", "Every Admin, Books and Compliance setup step, including how to build your company's filing cabinet.",
           ["48 setup steps", "A file-label builder for your folders", "A 12-month compliance calendar"]),
 "riltr": ("goals-vision", None, None, None),
 "gaap":  ("qbo-learning", None, None, None),
 "exit":  ("exit-plan", None, None, None),
}
